//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.4927
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbiSoft.EbIRC.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EbiSoft.EbIRC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Starting connection. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BeginConnection {
            get {
                return ResourceManager.GetString("BeginConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t connect server. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CannotConnectMessage {
            get {
                return ResourceManager.GetString("CannotConnectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t open URL. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CannotOpenURL {
            get {
                return ResourceManager.GetString("CannotOpenURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can&apos;t remove all profiles. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CannotRemoveAllProfileMessage {
            get {
                return ResourceManager.GetString("CannotRemoveAllProfileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input add channel name or nickname に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChannelAddDialogCaption {
            get {
                return ResourceManager.GetString("ChannelAddDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add receiver に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChannelAddDialogTitle {
            get {
                return ResourceManager.GetString("ChannelAddDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add receiver に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChannelControl_Add {
            get {
                return ResourceManager.GetString("ChannelControl_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Join に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChannelControl_Join {
            get {
                return ResourceManager.GetString("ChannelControl_Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Leave に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChannelControl_Leave {
            get {
                return ResourceManager.GetString("ChannelControl_Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Menu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChannelControl_NoContext {
            get {
                return ResourceManager.GetString("ChannelControl_NoContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add receiver for talk に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChannelControl_PrivateMessage {
            get {
                return ResourceManager.GetString("ChannelControl_PrivateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove from list に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChannelControl_Remove {
            get {
                return ResourceManager.GetString("ChannelControl_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;server&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChannelSelecterServerCaption {
            get {
                return ResourceManager.GetString("ChannelSelecterServerCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cleared logs. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClearedLog {
            get {
                return ResourceManager.GetString("ClearedLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comfirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Confim {
            get {
                return ResourceManager.GetString("Confim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connected to server. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConnectionMenuCaption {
            get {
                return ResourceManager.GetString("ConnectionMenuCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EbIRC is crashed. Please send EbIRC_ExceptionReport.txt to author. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CrashMessage {
            get {
                return ResourceManager.GetString("CrashMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EbIRC_ExceptionReport.txt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CrashReportFile {
            get {
                return ResourceManager.GetString("CrashReportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CTCP-Reply: {0} &apos;s {1} value is {2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CtcpReplyMessage {
            get {
                return ResourceManager.GetString("CtcpReplyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   http://iseebi.half-done.net/ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CtcpSource {
            get {
                return ResourceManager.GetString("CtcpSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EbIRC (.NET/Windows Mobile) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CtcpVersion {
            get {
                return ResourceManager.GetString("CtcpVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ASCII に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultEncoding {
            get {
                return ResourceManager.GetString("DefaultEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Default) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultProfileName {
            get {
                return ResourceManager.GetString("DefaultProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   servers.txt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultServerFileName {
            get {
                return ResourceManager.GetString("DefaultServerFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   irc.nara.wide.ad.jp
        ///irc.tokyo.wide.ad.jp
        ///irc.fujisawa.wide.ad.jp
        ///irc.huie.hokudai.ac.jp
        ///irc.media.kyoto-u.ac.jp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultServers {
            get {
                return ResourceManager.GetString("DefaultServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disconnect from server? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DisconnectConfim {
            get {
                return ResourceManager.GetString("DisconnectConfim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disconnected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is disconnected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DisconnectedUser {
            get {
                return ResourceManager.GetString("DisconnectedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disconnect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DisconnectMenuCaption {
            get {
                return ResourceManager.GetString("DisconnectMenuCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ASCII
        ///UTF-8 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EncodeList {
            get {
                return ResourceManager.GetString("EncodeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExitConfim {
            get {
                return ResourceManager.GetString("ExitConfim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed start. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FaildBoot {
            get {
                return ResourceManager.GetString("FaildBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   http://www.google.com/search?q={0}&amp;ie=utf-8&amp;oe=utf-8 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GoogleURL {
            get {
                return ResourceManager.GetString("GoogleURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input new nickname に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputNewNicknamePrompt {
            get {
                return ResourceManager.GetString("InputNewNicknamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input new nickname に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputNewNicknameTitle {
            get {
                return ResourceManager.GetString("InputNewNicknameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Joined to channel. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Joined {
            get {
                return ResourceManager.GetString("Joined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is now joined. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string JoinedUser {
            get {
                return ResourceManager.GetString("JoinedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You were kicked. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KickedMeMessage {
            get {
                return ResourceManager.GetString("KickedMeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} kicked {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KickedMessage {
            get {
                return ResourceManager.GetString("KickedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   leaved に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Leaved {
            get {
                return ResourceManager.GetString("Leaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is leaved. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LeavedUser {
            get {
                return ResourceManager.GetString("LeavedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogFormat {
            get {
                return ResourceManager.GetString("LogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} changes mode {1} {2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModeChanged {
            get {
                return ResourceManager.GetString("ModeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mode: {0} {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModeReceived {
            get {
                return ResourceManager.GetString("ModeReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is changed nickname to {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NicknameChangedMessage {
            get {
                return ResourceManager.GetString("NicknameChangedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoticeLogFormat {
            get {
                return ResourceManager.GetString("NoticeLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No server configs. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NullServerSettingError {
            get {
                return ResourceManager.GetString("NullServerSettingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0:D3} {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NumericReplyLogFormat {
            get {
                return ResourceManager.GetString("NumericReplyLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}&gt; {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PrivmsgLogFormat {
            get {
                return ResourceManager.GetString("PrivmsgLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New profile name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProfileAddDialogCaption {
            get {
                return ResourceManager.GetString("ProfileAddDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add profile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProfileAddDialogTitle {
            get {
                return ResourceManager.GetString("ProfileAddDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EbIRC &lt;Server messages&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServerMessageTitlebar {
            get {
                return ResourceManager.GetString("ServerMessageTitlebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server messages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServerMessageTopicbar {
            get {
                return ResourceManager.GetString("ServerMessageTopicbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EbIRC.settings.xml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingFileName {
            get {
                return ResourceManager.GetString("SettingFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch ch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SwitcherMenuCaption {
            get {
                return ResourceManager.GetString("SwitcherMenuCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0:00}:{1:00} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TimeFormat {
            get {
                return ResourceManager.GetString("TimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EbIRC {0}({1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitlebarFormat {
            get {
                return ResourceManager.GetString("TitlebarFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TopicbarFormat {
            get {
                return ResourceManager.GetString("TopicbarFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} changed topic to {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TopicChanged {
            get {
                return ResourceManager.GetString("TopicChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Topic: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TopicReceived {
            get {
                return ResourceManager.GetString("TopicReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Now members: {0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UsersLogFormat {
            get {
                return ResourceManager.GetString("UsersLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EbIRC Ver{0}.{1:D2} Release.{2} Copyright(C) 2006-2007 Shin ISE. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VersionInfomation {
            get {
                return ResourceManager.GetString("VersionInfomation", resourceCulture);
            }
        }
    }
}
